name: Sample Build, Test & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker system prune -f
          docker compose -f docker/ci.docker-compose.yml build

      - name: Run Tests
        run: |
          docker compose -f docker/ci.docker-compose.yml run --rm app sh -c "./gradlew test"

      - name: Deploy
        run: |
          docker compose -f docker/ci.docker-compose.yml down
          docker compose -f docker/ci.docker-compose.yml up -d --build
          docker image prune -af

